In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("data/E2.csv")
matches = df[["HomeTeam", "AwayTeam", "FTHG", "FTAG"]].copy()
matches.head()

       HomeTeam     AwayTeam  FTHG  FTAG
0      Barnsley    Mansfield     1     2
1    Birmingham      Reading     1     1
2   Bristol Rvs  Northampton     1     0
3        Burton      Lincoln     2     3
4  Crawley Town    Blackpool     2     1

In [3]:
avg_home_goals = matches["FTHG"].mean()
avg_away_goals = matches["FTAG"].mean()

print("Average home goals per game:", round(avg_home_goals, 3))
print("Average away goals per game:", round(avg_away_goals, 3))

Average home goals per game: 1.404
Average away goals per game: 1.181

In [5]:
home = matches.groupby("HomeTeam").agg(
    home_scored=("FTHG", "mean"),
    home_conceded=("FTAG", "mean")
)
home.head(10)

              home_scored  home_conceded
HomeTeam
Barnsley         1.434783       1.565217
Birmingham       2.043478       0.478261
Blackpool        1.521739       1.260870
Bolton           1.565217       1.391304
Bristol Rvs      1.347826       1.434783
Burton           1.304348       1.478261
Cambridge        1.086957       1.434783
Charlton         1.652174       0.695652
Crawley Town     1.347826       1.521739
Exeter           1.304348       1.434783

In [7]:
away = matches.groupby("AwayTeam").agg(
    away_scored=("FTAG", "mean"),
    away_conceded=("FTHG", "mean")
)
away.head(10)

              away_scored  away_conceded
AwayTeam
Barnsley         1.565217       1.608696
Birmingham       1.608696       0.869565
Blackpool        1.608696       1.347826
Bolton           1.347826       1.652174
Bristol Rvs      0.565217       1.869565
Burton           0.826087       1.391304
Cambridge        0.869565       1.739130
Charlton         1.260870       1.173913
Crawley Town     1.130435       2.086957
Exeter           0.826087       1.391304

In [9]:
strength = home.join(away)
strength.head(10)

              home_scored  home_conceded  away_scored  away_conceded
HomeTeam
Barnsley         1.434783       1.565217     1.565217       1.608696
Birmingham       2.043478       0.478261     1.608696       0.869565
Blackpool        1.521739       1.260870     1.608696       1.347826
Bolton           1.565217       1.391304     1.347826       1.652174
Bristol Rvs      1.347826       1.434783     0.565217       1.869565
Burton           1.304348       1.478261     0.826087       1.391304
Cambridge        1.086957       1.434783     0.869565       1.739130
Charlton         1.652174       0.695652     1.260870       1.173913
Crawley Town     1.347826       1.521739     1.130435       2.086957
Exeter           1.304348       1.434783     0.826087       1.391304